Class {
	#name : 'LevenshteinSorterTestContext',
	#superclass : 'Object',
	#instVars : [
		'currentWord'
	],
	#category : 'Levenshtein-Sorter-Tests',
	#package : 'Levenshtein-Sorter-Tests'
}

{ #category : 'accessing' }
LevenshteinSorterTestContext >> currentWord [

    ^ currentWord
]

{ #category : 'accessing' }
LevenshteinSorterTestContext >> currentWord: aString [

    currentWord := aString
]
